### ISSUE TITLE
.u-mb-x1

### ISSUE THREAD

**Issue by aldreth** [RaspberryPiFoundation/Bits#88]
@Jonic Just a question - why doesn't `.u-mb-x1` exist?

**Comment by Jonic** [comment]
@aldreth You know what? I don't know! Oversight, it would seem - sorry about that!

I'm not entirely happy with the margin and padding utilities anyway. I think they encourage us to just slap them on everything all over the place instead of actually deciding on standard paddings/margins, so they're something I'd really like to sort out in future. Did you need the `u-mb-x1` urgently? For now you can access the `$spacing` var (equal to one spacing unit) in the Sass to apply the margin there.

**Comment by aldreth** [comment]
Don't need it at all, just spotted it was missing.

I think the margin & padding utility classes are really useful, especially responsive variants.

**Comment by aldreth** [comment]
I think there's loads of things to figure out as more of us start using this repo. But I really like it in general!
